// Тексты страницы /apps/davomat — учёт рабочего времени по лицу: терминалы, табель, выгрузка в 1С. 5 локалей инлайном.
import type { AppPage } from "./appsContent";

export const DAVOMAT: Record<string, AppPage> = {
  ru: {
    metaTitle: "SAT Davomat — учёт рабочего времени по лицу: табель и выгрузка в 1С | SAT Solutions",
    metaDesc: "Программа учёта рабочего времени: приход и уход по лицу или карте, табель по сотрудникам, опоздания и переработки, выгрузка табеля в 1С, несколько объектов в одном кабинете. Терминалы ZKTeco, Dahua и Hikvision.",
    h1: "SAT Davomat — учёт рабочего времени по лицу",
    intro: "Сотрудник подходит к терминалу, тот узнаёт лицо за доли секунды и отмечает приход. Бухгалтер в конце месяца открывает готовый табель, а не собирает журналы охраны. Программа работает с терминалами, которые уже стоят на проходной.",
    screensTitle: "Что видно в кабинете",
    screens: ["Кто на работе сейчас", "Табель за месяц", "Опоздания", "Выгрузка в 1С"],
    forWhomTitle: "Возможности",
    forWhom: [
      { t: "Приход и уход по лицу", d: "Отметка занимает меньше секунды, отмечаться за другого нельзя, пропуск забыть невозможно." },
      { t: "Табель по сотрудникам", d: "Часы за смену, день и месяц. Отпуск, больничный и командировку отмечает кадровик." },
      { t: "Опоздания и переработки", d: "График работы задаётся по подразделениям, программа сама считает отклонения от него." },
      { t: "Выгрузка в 1С", d: "Готовый табель переносится в 1С обработкой, без ручного переписывания часов." },
      { t: "Несколько объектов", d: "Офис, склад и цех в одном кабинете. Видно, кто на работе прямо сейчас и на какой площадке." },
      { t: "Отчёты руководителю", d: "Выгрузка в Excel, отчёты по подразделениям и по сотруднику за любой период." },
    ],
    secondTitle: "Кому подходит",
    second: [
      { t: "Производствам и складам", d: "Смены, ночные и переработки считаются автоматически, спорные часы видно по записям проходов." },
      { t: "Офисам", d: "Гибкое начало дня, обед и удалённые дни — правила настраиваются, а не считаются вручную." },
      { t: "Сетям точек", d: "Кафе, магазины и филиалы: один кабинет на всю сеть, отдельный график для каждой точки." },
      { t: "Строительным объектам", d: "Проходная в бытовке, терминал на аккумуляторе и мобильном интернете, учёт бригад по объектам." },
    ],
    howTitle: "Как внедряем",
    how: [
      { t: "1. Считаем проходные", d: "Смотрим, сколько входов и выходов, есть ли турникеты и какая техника уже стоит." },
      { t: "2. Ставим терминалы", d: "Монтируем терминалы распознавания лиц или подключаем существующие, при необходимости ставим турникет." },
      { t: "3. Заводим сотрудников", d: "Регистрируем лица, загружаем список из 1С или Excel, задаём графики работы и подразделения." },
      { t: "4. Обучаем и передаём", d: "Показываем кабинет кадровику и бухгалтеру, настраиваем выгрузку в 1С и отчёты." },
    ],
    techTitle: "С какой техникой работает",
    techText: "Подходят распространённые терминалы учёта рабочего времени. Совместимость проверяем на осмотре — часто менять ничего не нужно.",
    tech: [
      "Терминалы распознавания лиц ZKTeco, Dahua и Hikvision",
      "Считыватели карт и отпечатков пальцев",
      "Турникеты и калитки",
      "1С: перенос табеля обработкой",
      "Интернет на объекте и небольшой шлюз",
    ],
    faqTitle: "Частые вопросы",
    faq: [
      { q: "Законно ли собирать лица сотрудников?", a: "Да, при согласии работника и правильном оформлении в правилах компании. Помогаем подготовить согласие и положение об учёте времени." },
      { q: "Что делать с сотрудниками без смартфона?", a: "Смартфон не нужен: сотрудник отмечается лицом или картой на терминале." },
      { q: "Работает ли учёт без интернета?", a: "Да. Терминал хранит отметки у себя и передаёт их, когда связь появится." },
      { q: "Можно ли учитывать несколько смен и ночные?", a: "Да, графики настраиваются по подразделениям, включая ночные смены и скользящие графики." },
    ],
    ctaTitle: "Посчитаем учёт времени для вашей компании",
    ctaText: "Скажите, сколько сотрудников и проходных, — подберём терминалы и покажем кабинет на демонстрации.",
    ctaButton: "Оставить заявку",
    otherApp: "Приложение для жителей ЖК — SAT Uy",
  },
  uz: {
    metaTitle: "SAT Davomat — yuz orqali ish vaqti hisobi: tabel va 1Cga yuklash | SAT Solutions",
    metaDesc: "Ish vaqtini hisobga olish dasturi: yuz yoki karta orqali kelish-ketish, xodimlar boʻyicha tabel, kechikish va ortiqcha ish, tabelni 1Cga yuklash, bitta kabinetda bir nechta obyekt. ZKTeco, Dahua va Hikvision terminallari.",
    h1: "SAT Davomat — yuz orqali ish vaqtini hisobga olish",
    intro: "Xodim terminalga yaqinlashadi, u yuzni bir soniyadan tez taniydi va kelishni qayd etadi. Buxgalter oy oxirida tayyor tabelni ochadi, qorovul daftarlarini yigʻmaydi. Dastur nazorat-oʻtkazish punktidagi terminallar bilan ishlaydi.",
    screensTitle: "Kabinetda nima koʻrinadi",
    screens: ["Hozir kim ishda", "Oylik tabel", "Kechikishlar", "1Cga yuklash"],
    forWhomTitle: "Imkoniyatlar",
    forWhom: [
      { t: "Yuz orqali kelish va ketish", d: "Qayd bir soniyadan kam vaqt oladi, boshqa odam oʻrniga belgilab boʻlmaydi, ruxsatnomani unutish ham mumkin emas." },
      { t: "Xodimlar boʻyicha tabel", d: "Smena, kun va oy boʻyicha soatlar. Ta’til, kasallik va xizmat safarini kadrlar xodimi belgilaydi." },
      { t: "Kechikish va ortiqcha ish", d: "Ish grafigi boʻlimlar boʻyicha beriladi, dastur undan chetlanishlarni oʻzi hisoblaydi." },
      { t: "1Cga yuklash", d: "Tayyor tabel maxsus ishlov bilan 1Cga oʻtkaziladi, soatlarni qoʻlda koʻchirish shart emas." },
      { t: "Bir nechta obyekt", d: "Ofis, ombor va sex bitta kabinetda. Hozir kim ishda va qaysi maydonchada ekani koʻrinadi." },
      { t: "Rahbarga hisobotlar", d: "Excelga yuklash, boʻlimlar va har bir xodim boʻyicha istalgan davr hisobotlari." },
    ],
    secondTitle: "Kimlarga mos keladi",
    second: [
      { t: "Ishlab chiqarish va omborlarga", d: "Smenalar, tungi ishlar va ortiqcha soatlar avtomatik hisoblanadi, bahsli soatlar oʻtish yozuvlarida koʻrinadi." },
      { t: "Ofislarga", d: "Moslashuvchan ish boshlanishi, tushlik va masofaviy kunlar — qoidalar sozlanadi, qoʻlda sanalmaydi." },
      { t: "Tarmoq nuqtalariga", d: "Kafe, doʻkon va filiallar: butun tarmoq uchun bitta kabinet, har bir nuqtaga alohida grafik." },
      { t: "Qurilish obyektlariga", d: "Vagon-uydagi oʻtish punkti, akkumulyator va mobil internetdagi terminal, brigadalar hisobi." },
    ],
    howTitle: "Qanday joriy qilamiz",
    how: [
      { t: "1. Oʻtish punktlarini sanaymiz", d: "Nechta kirish va chiqish borligini, turniketlar va mavjud texnikani koʻramiz." },
      { t: "2. Terminal oʻrnatamiz", d: "Yuzni tanish terminallarini oʻrnatamiz yoki mavjudini ulaymiz, kerak boʻlsa turniket qoʻyamiz." },
      { t: "3. Xodimlarni kiritamiz", d: "Yuzlarni roʻyxatga olamiz, roʻyxatni 1C yoki Exceldan yuklaymiz, grafik va boʻlimlarni belgilaymiz." },
      { t: "4. Oʻrgatamiz va topshiramiz", d: "Kadrlar va buxgalteriyaga kabinetni koʻrsatamiz, 1Cga yuklash va hisobotlarni sozlaymiz." },
    ],
    techTitle: "Qaysi texnika bilan ishlaydi",
    techText: "Keng tarqalgan ish vaqti terminallariga mos keladi. Moslikni koʻrik paytida tekshiramiz — koʻpincha hech narsani almashtirish shart emas.",
    tech: [
      "ZKTeco, Dahua va Hikvision yuzni tanish terminallari",
      "Karta va barmoq izi oʻqigichlari",
      "Turniketlar va darvozachalar",
      "1C: tabelni maxsus ishlov bilan koʻchirish",
      "Obyektda internet va kichik shlyuz",
    ],
    faqTitle: "Koʻp beriladigan savollar",
    faq: [
      { q: "Xodimlar yuzini yigʻish qonuniymi?", a: "Ha, xodim roziligi va kompaniya qoidalarida toʻgʻri rasmiylashtirish bilan. Rozilik va ish vaqti hisobi nizomini tayyorlashda yordam beramiz." },
      { q: "Smartfoni yoʻq xodimlar-chi?", a: "Smartfon kerak emas: xodim terminalda yuzi yoki kartasi bilan belgilanadi." },
      { q: "Internetsiz ishlaydimi?", a: "Ha. Terminal qaydlarni oʻzida saqlaydi va aloqa paydo boʻlganda yuboradi." },
      { q: "Bir nechta smena va tungi ishni hisoblasa boʻladimi?", a: "Ha, grafiklar boʻlimlar boʻyicha, jumladan tungi va siljuvchi smenalar bilan sozlanadi." },
    ],
    ctaTitle: "Kompaniyangiz uchun hisoblab beramiz",
    ctaText: "Xodimlar va oʻtish punktlari sonini ayting — terminallarni tanlaymiz va kabinetni namoyish qilamiz.",
    ctaButton: "Ariza qoldirish",
    otherApp: "TJM aholisi uchun ilova — SAT Uy",
  },
  en: {
    metaTitle: "SAT Davomat — face-based time tracking with timesheets and 1C export | SAT Solutions",
    metaDesc: "Time and attendance software: face or card check-in, per-employee timesheets, late arrivals and overtime, timesheet export to 1C, several sites in one dashboard. Works with ZKTeco, Dahua and Hikvision terminals.",
    h1: "SAT Davomat — face-based time and attendance",
    intro: "An employee steps up to the terminal, it recognises the face in a fraction of a second and records the arrival. At month end the accountant opens a finished timesheet instead of collecting guard logbooks. The software works with terminals already installed at the entrance.",
    screensTitle: "What the dashboard shows",
    screens: ["Who is at work now", "Monthly timesheet", "Late arrivals", "Export to 1C"],
    forWhomTitle: "Features",
    forWhom: [
      { t: "Face check-in and check-out", d: "A check-in takes under a second, nobody can clock in for a colleague and no pass can be forgotten." },
      { t: "Per-employee timesheets", d: "Hours per shift, day and month. HR marks holidays, sick leave and business trips." },
      { t: "Late arrivals and overtime", d: "Work schedules are set per department and the system calculates deviations by itself." },
      { t: "Export to 1C", d: "The finished timesheet moves into 1C through a processing file, with no hours retyped by hand." },
      { t: "Multiple sites", d: "Office, warehouse and workshop in one dashboard, with a live view of who is at work and where." },
      { t: "Reports for management", d: "Excel export, reports by department and per employee for any period." },
    ],
    secondTitle: "Who it fits",
    second: [
      { t: "Production and warehouses", d: "Shifts, night hours and overtime are calculated automatically; disputed hours are backed by entry records." },
      { t: "Offices", d: "Flexible start, lunch breaks and remote days are configured as rules instead of being counted by hand." },
      { t: "Retail chains", d: "Cafés, shops and branches: one dashboard for the whole network with a schedule per location." },
      { t: "Construction sites", d: "A checkpoint in the site cabin, a terminal on battery and mobile internet, crews tracked per site." },
    ],
    howTitle: "How we roll it out",
    how: [
      { t: "1. Count the checkpoints", d: "We look at how many entries and exits there are, whether turnstiles exist and what hardware is already installed." },
      { t: "2. Install terminals", d: "We mount face terminals or connect existing ones, and add a turnstile where it is needed." },
      { t: "3. Enrol employees", d: "We register faces, import the staff list from 1C or Excel and set schedules and departments." },
      { t: "4. Train and hand over", d: "We show the dashboard to HR and accounting and set up the 1C export and reports." },
    ],
    techTitle: "Supported hardware",
    techText: "Common time and attendance terminals are supported. We confirm compatibility during the survey — usually nothing needs replacing.",
    tech: [
      "ZKTeco, Dahua and Hikvision face terminals",
      "Card and fingerprint readers",
      "Turnstiles and gates",
      "1C: timesheet transfer via a processing file",
      "Internet on site and a small gateway",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "Is collecting employees' faces legal?", a: "Yes, with the employee's consent and proper wording in company rules. We help prepare the consent form and the time-tracking policy." },
      { q: "What about employees without a smartphone?", a: "No smartphone is needed: the employee checks in at the terminal by face or card." },
      { q: "Does tracking work without internet?", a: "Yes. The terminal stores records locally and uploads them once the connection is back." },
      { q: "Can it handle several shifts and night work?", a: "Yes, schedules are configured per department, including night and rotating shifts." },
    ],
    ctaTitle: "We will scope time tracking for your company",
    ctaText: "Tell us the headcount and the number of checkpoints — we will pick the terminals and demo the dashboard.",
    ctaButton: "Request a demo",
    otherApp: "Resident app for apartment complexes — SAT Uy",
  },
  tr: {
    metaTitle: "SAT Davomat — yüzle mesai takibi: puantaj ve 1C aktarımı | SAT Solutions",
    metaDesc: "Personel devam takibi yazılımı: yüz veya kartla giriş-çıkış, personel bazlı puantaj, geç kalma ve fazla mesai, puantajın 1C’ye aktarımı, tek panelde birden çok saha. ZKTeco, Dahua ve Hikvision terminalleriyle çalışır.",
    h1: "SAT Davomat — yüz tanımayla mesai takibi",
    intro: "Personel terminale yaklaşır, cihaz yüzü saniyenin altında tanır ve girişi kaydeder. Ay sonunda muhasebe, güvenlik defterlerini toplamak yerine hazır puantajı açar. Yazılım girişte zaten kurulu terminallerle çalışır.",
    screensTitle: "Panelde ne görünür",
    screens: ["Şu an işte olanlar", "Aylık puantaj", "Geç kalmalar", "1C aktarımı"],
    forWhomTitle: "Özellikler",
    forWhom: [
      { t: "Yüzle giriş ve çıkış", d: "Kayıt bir saniyeden kısa sürer, başkası yerine okutulamaz, kart unutma sorunu kalmaz." },
      { t: "Personel bazlı puantaj", d: "Vardiya, gün ve ay bazında saatler. İzin, rapor ve görevlendirmeyi İK işaretler." },
      { t: "Geç kalma ve fazla mesai", d: "Çalışma programı departman bazında tanımlanır, sapmaları sistem kendisi hesaplar." },
      { t: "1C aktarımı", d: "Hazır puantaj işleme dosyasıyla 1C’ye aktarılır; saatler elle yeniden yazılmaz." },
      { t: "Birden çok saha", d: "Ofis, depo ve atölye tek panelde; kimin nerede çalıştığı anlık görünür." },
      { t: "Yönetime raporlar", d: "Excel aktarımı, departman ve personel bazında istenen dönem raporları." },
    ],
    secondTitle: "Kimler için uygun",
    second: [
      { t: "Üretim ve depolar", d: "Vardiya, gece ve fazla mesai otomatik hesaplanır; tartışmalı saatler geçiş kayıtlarıyla desteklenir." },
      { t: "Ofisler", d: "Esnek başlangıç, öğle arası ve uzaktan günler kural olarak tanımlanır, elle sayılmaz." },
      { t: "Zincir işletmeler", d: "Kafe, mağaza ve şubeler: tüm ağ için tek panel, her nokta için ayrı program." },
      { t: "Şantiyeler", d: "Şantiye kabininde geçiş noktası, aküyle ve mobil internetle çalışan terminal, ekip bazlı takip." },
    ],
    howTitle: "Nasıl devreye alıyoruz",
    how: [
      { t: "1. Geçiş noktalarını sayıyoruz", d: "Kaç giriş ve çıkış var, turnike var mı, hangi donanım kurulu — bunlara bakıyoruz." },
      { t: "2. Terminalleri kuruyoruz", d: "Yüz terminallerini montajlıyor ya da mevcutları bağlıyoruz; gerekirse turnike ekliyoruz." },
      { t: "3. Personeli tanımlıyoruz", d: "Yüzleri kaydediyor, listeyi 1C veya Excel’den alıyor, program ve departmanları giriyoruz." },
      { t: "4. Eğitip teslim ediyoruz", d: "Paneli İK ve muhasebeye gösteriyor, 1C aktarımını ve raporları ayarlıyoruz." },
    ],
    techTitle: "Hangi donanımla çalışır",
    techText: "Yaygın mesai takip terminalleri desteklenir. Uyumluluğu keşifte doğruluyoruz; çoğunlukla değişiklik gerekmez.",
    tech: [
      "ZKTeco, Dahua ve Hikvision yüz terminalleri",
      "Kart ve parmak izi okuyucuları",
      "Turnikeler ve kapılar",
      "1C: puantajın işleme dosyasıyla aktarımı",
      "Sahada internet ve küçük ağ geçidi",
    ],
    faqTitle: "Sık sorulan sorular",
    faq: [
      { q: "Personel yüzü toplamak yasal mı?", a: "Evet, çalışanın rızası ve şirket kurallarında doğru düzenleme ile. Rıza metni ve mesai takip yönergesini hazırlamaya yardım ediyoruz." },
      { q: "Akıllı telefonu olmayan personel ne yapacak?", a: "Telefon gerekmez: personel terminalde yüz ya da kartla okutur." },
      { q: "İnternetsiz çalışır mı?", a: "Evet. Terminal kayıtları kendinde tutar ve bağlantı gelince aktarır." },
      { q: "Birden çok vardiya ve gece mesaisi olur mu?", a: "Evet, programlar departman bazında tanımlanır; gece ve dönüşümlü vardiyalar dâhil." },
    ],
    ctaTitle: "Şirketiniz için mesai takibini hesaplayalım",
    ctaText: "Personel sayısını ve geçiş noktalarını söyleyin — terminalleri seçip paneli gösterelim.",
    ctaButton: "Talep gönderin",
    otherApp: "Konut siteleri için uygulama — SAT Uy",
  },
  zh: {
    metaTitle: "SAT Davomat——人脸考勤：考勤表与导出到 1C | SAT Solutions",
    metaDesc: "考勤管理软件：人脸或刷卡打卡、按员工统计考勤表、迟到与加班、考勤表导出到 1C、一个后台管理多个场所，兼容 ZKTeco、大华与海康终端。",
    h1: "SAT Davomat——人脸考勤",
    intro: "员工走到终端前，设备在一秒内识别人脸并记录上班时间。月末会计直接打开成型的考勤表，不必再收集门卫记录。软件可对接门口已安装的终端。",
    screensTitle: "后台可见内容",
    screens: ["当前在岗人员", "月度考勤表", "迟到记录", "导出到 1C"],
    forWhomTitle: "功能",
    forWhom: [
      { t: "人脸上下班打卡", d: "打卡不到一秒，无法代打卡，也不存在忘带卡的问题。" },
      { t: "按员工统计考勤", d: "按班次、按日、按月统计工时；休假、病假与出差由人事标注。" },
      { t: "迟到与加班", d: "按部门设置班表，系统自动计算与班表的偏差。" },
      { t: "导出到 1C", d: "成型的考勤表通过处理文件导入 1C，无需手工誊写工时。" },
      { t: "多场所管理", d: "办公室、仓库与车间集中在一个后台，实时显示谁在岗、在哪个场所。" },
      { t: "管理层报表", d: "支持导出 Excel，可按部门与员工生成任意周期报表。" },
    ],
    secondTitle: "适用对象",
    second: [
      { t: "生产与仓储", d: "班次、夜班与加班自动计算，有争议的工时可凭通行记录核对。" },
      { t: "办公室", d: "弹性上班、午休与远程办公以规则配置，无需人工统计。" },
      { t: "连锁门店", d: "餐饮、零售与分支机构：全网一个后台，每个门店独立班表。" },
      { t: "施工现场", d: "工棚设通行点，终端可用电池与移动网络，按项目统计班组。" },
    ],
    howTitle: "实施步骤",
    how: [
      { t: "1. 统计通行点", d: "确认出入口数量、是否有闸机以及现有设备情况。" },
      { t: "2. 安装终端", d: "安装人脸终端或接入现有设备，必要时增设闸机。" },
      { t: "3. 录入员工", d: "采集人脸，从 1C 或 Excel 导入名单，设置班表与部门。" },
      { t: "4. 培训与交付", d: "向人事与财务演示后台，配置 1C 导出与报表。" },
    ],
    techTitle: "支持的设备",
    techText: "支持常见考勤终端，兼容性在勘察时确认，多数情况下无需更换设备。",
    tech: [
      "ZKTeco、大华与海康人脸终端",
      "刷卡与指纹读头",
      "闸机与通道门",
      "1C：通过处理文件导入考勤表",
      "现场网络与小型网关",
    ],
    faqTitle: "常见问题",
    faq: [
      { q: "采集员工人脸是否合法？", a: "在取得员工同意并在公司制度中作出规范的前提下合法。我们可协助准备同意书与考勤管理制度。" },
      { q: "没有智能手机的员工怎么办？", a: "无需手机：员工在终端用人脸或刷卡打卡即可。" },
      { q: "断网还能考勤吗？", a: "可以。终端本地保存记录，网络恢复后自动上传。" },
      { q: "能处理多班次与夜班吗？", a: "可以，班表按部门配置，支持夜班与轮班。" },
    ],
    ctaTitle: "为贵公司核算考勤方案",
    ctaText: "告诉我们员工人数与通行点数量，我们选型终端并演示后台。",
    ctaButton: "提交需求",
    otherApp: "小区住户应用——SAT Uy",
  },
};
