// Тексты страницы /apps/uy — приложение SAT Uy для жителей ЖК и кабинет управляющей компании. 5 локалей инлайном.
import type { AppPage } from "./appsContent";

export const UY: Record<string, AppPage> = {
  ru: {
    metaTitle: "SAT Uy — приложение жителям ЖК: домофон и гости по QR",
    metaDesc: "Приложение для жителей жилого комплекса: открыть подъезд и шлагбаум с телефона, пропуск гостю по QR-коду, звонок домофона на телефон, заявки в УК, счёт за месяц и оплата. Кабинет управляющей компании: жители, заявки, начисления, журнал.",
    h1: "SAT Uy — приложение жителям ЖК и кабинет управляющей компании",
    intro: "Жители открывают двери телефоном, вызывают лифтёра и сантехника без звонков диспетчеру и видят, за что платят. Управляющая компания ведёт заявки, начисления и журнал проходов в одном кабинете. Приложение работает с домофонами, терминалами распознавания лиц и контроллерами, которые стоят на объекте.",
    screensTitle: "Что видит житель",
    screens: ["Двери дома", "Гостевой пропуск", "Заявки в УК", "Счёт за месяц"],
    forWhomTitle: "Жителям",
    forWhom: [
      { t: "Подъезд и шлагбаум с телефона", d: "Свои двери видны сразу на главном экране, открытие — одно нажатие, даже когда телефон в кармане у ворот." },
      { t: "Гость по ссылке и QR-коду", d: "Житель выдаёт пропуск на время или на один визит. Гость открывает дверь ссылкой или подносит QR к терминалу." },
      { t: "Звонок домофона на телефон", d: "Видно, кто у двери, и дверь открывается прямо из уведомления — даже если жителя нет дома." },
      { t: "Заявки в управляющую компанию", d: "Заявка проходит этапы «принята», «в работе», «выполнена», видно исполнителя и ответы диспетчера." },
      { t: "Счёт и оплата", d: "Начисления по месяцам, долг и оплата через Click. Показания счётчиков житель передаёт из приложения." },
      { t: "Семья и арендаторы", d: "Владелец приглашает членов семьи и арендатора на срок, а счёт открывает по своему усмотрению." },
    ],
    secondTitle: "Управляющей компании",
    second: [
      { t: "Кабинет вместо тетради", d: "Дома, квартиры, жители и права доступа в одном месте. Открыть дверь можно и из кабинета." },
      { t: "Заявки с исполнителями", d: "Диспетчер назначает сантехника или электрика, житель видит этап, а в истории остаётся кто, когда и что сделал." },
      { t: "Начисления и оплаты", d: "Тарифы по площади, по квартире или по жильцам. Готовые начисления можно загрузить из Excel или 1С." },
      { t: "Новости и чат", d: "Объявление об отключении воды уходит всему дому уведомлением, а житель отвечает в чате." },
      { t: "Журнал проходов", d: "Кто открыл дверь, когда и чем: телефоном, лицом, картой или гостевым QR-кодом." },
      { t: "Безопасность", d: "Роли управляющего и диспетчера, второй фактор при входе, неизменяемый журнал действий сотрудников." },
    ],
    howTitle: "Как подключаем",
    how: [
      { t: "1. Смотрим объект", d: "Проверяем домофоны, контроллеры, сеть и питание. Рабочую технику оставляем, недостающее дополняем." },
      { t: "2. Ставим шлюз", d: "Небольшой шлюз в серверной связывает технику с сервером SAT. Пароли оборудования остаются на объекте." },
      { t: "3. Заводим дома и квартиры", d: "Переносим список квартир и жителей, назначаем сотрудников УК и их права." },
      { t: "4. Запускаем жителей", d: "Житель ставит приложение и входит по своей почте. Управляющей компании показываем кабинет и обучаем диспетчера." },
    ],
    techTitle: "С какой техникой работает",
    techText: "Приложение управляет оборудованием по сети, поэтому подходит большинство современных систем. Проверяем совместимость на осмотре.",
    tech: [
      "Вызывные панели и домофоны Hikvision и Dahua",
      "Терминалы распознавания лиц Dahua, в том числе проход по QR-коду",
      "Контроллеры дверей и шлагбаумов ZKTeco",
      "Электромагнитные замки, доводчики, кнопки выхода",
      "Интернет на объекте и небольшой шлюз в серверной",
    ],
    faqTitle: "Частые вопросы",
    faq: [
      { q: "Нужно ли жителю платить за приложение?", a: "Условия определяет управляющая компания: чаще всего приложение входит в обслуживание дома. Мы обсуждаем тариф с УК, а не с каждым жителем." },
      { q: "Что будет, если житель сменит телефон?", a: "Вход по почте с кодом, поэтому на новом телефоне достаточно войти заново. Старый телефон доступ теряет." },
      { q: "Как не пустить чужого человека в чужую квартиру?", a: "Квартиру заводит управляющая компания и привязывает к ней почту владельца. Остальных жителей приглашает владелец, а арендатора — на срок." },
      { q: "Работает ли приложение без интернета в доме?", a: "Проход по лицу и карте решает сам терминал, поэтому работает всегда. Открытие с телефона, гостевые QR и заявки требуют связи." },
      { q: "Можно ли подключить только один подъезд?", a: "Да. Начать можно с одного подъезда или одного шлагбаума и расширять постепенно." },
    ],
    ctaTitle: "Покажем SAT Uy управляющей компании",
    ctaText: "Проведём демонстрацию на вашем объекте и посчитаем, что нужно для запуска: какую технику оставляем, что добавляем.",
    ctaButton: "Оставить заявку",
    otherApp: "Учёт рабочего времени — SAT Davomat",
  },
  uz: {
    metaTitle: "SAT Uy — TJM ilovasi: domofon va mehmonlar QR orqali",
    metaDesc: "Turar joy majmuasi aholisi uchun ilova: yoʻlak va shlagbaumni telefondan ochish, mehmonga QR-kodli ruxsatnoma, domofon qoʻngʻirogʻi telefonga, BKga arizalar, oylik hisob va toʻlov. Boshqaruv kompaniyasi kabineti ham bor.",
    h1: "SAT Uy — aholiga ilova va boshqaruv kompaniyasiga kabinet",
    intro: "Aholi eshiklarni telefon bilan ochadi, santexnik yoki elektrikni dispetcherga qoʻngʻiroq qilmasdan chaqiradi va nima uchun toʻlayotganini koʻradi. Boshqaruv kompaniyasi arizalar, hisob-kitob va oʻtishlar jurnalini bitta kabinetda yuritadi. Ilova obyektdagi domofonlar, yuzni tanish terminallari va kontrollerlar bilan ishlaydi.",
    screensTitle: "Yashovchi nimani koʻradi",
    screens: ["Uy eshiklari", "Mehmon ruxsatnomasi", "BKga arizalar", "Oylik hisob"],
    forWhomTitle: "Aholi uchun",
    forWhom: [
      { t: "Yoʻlak va shlagbaum telefondan", d: "Oʻz eshiklari bosh ekranda koʻrinadi, ochish — bitta bosish, hatto telefon choʻntakda boʻlsa ham." },
      { t: "Mehmon havola va QR bilan", d: "Yashovchi muddatli yoki bir martalik ruxsatnoma beradi. Mehmon havoladan ochadi yoki QRni terminalga koʻrsatadi." },
      { t: "Domofon qoʻngʻirogʻi telefonga", d: "Eshik oldida kim turgani koʻrinadi, eshikni bildirishnomadan ochish mumkin — uyda boʻlmasangiz ham." },
      { t: "Boshqaruv kompaniyasiga arizalar", d: "Ariza «qabul qilindi», «bajarilmoqda», «bajarildi» bosqichlaridan oʻtadi; ijrochi va dispetcher javobi koʻrinadi." },
      { t: "Hisob va toʻlov", d: "Oylar boʻyicha hisob, qarz va Click orqali toʻlov. Hisoblagich koʻrsatkichlari ham ilovadan yuboriladi." },
      { t: "Oila va ijarachilar", d: "Egasi oila a’zolarini va ijarachini muddatga taklif qiladi, hisobni koʻrishni esa oʻzi hal qiladi." },
    ],
    secondTitle: "Boshqaruv kompaniyasiga",
    second: [
      { t: "Daftar oʻrniga kabinet", d: "Uylar, xonadonlar, yashovchilar va ruxsatlar bir joyda. Eshikni kabinetdan ham ochish mumkin." },
      { t: "Arizalar va ijrochilar", d: "Dispetcher santexnik yoki elektrikni tayinlaydi, yashovchi bosqichni koʻradi, tarixda kim nima qilgani qoladi." },
      { t: "Hisob-kitob va toʻlovlar", d: "Tariflar maydon, xonadon yoki yashovchilar soni boʻyicha. Tayyor hisob Excel yoki 1Cdan yuklanadi." },
      { t: "Yangiliklar va chat", d: "Suv oʻchishi haqidagi e’lon butun uyga bildirishnoma boʻlib boradi, yashovchi chatda javob yozadi." },
      { t: "Oʻtishlar jurnali", d: "Kim, qachon va nima bilan ochgani: telefon, yuz, karta yoki mehmon QR-kodi." },
      { t: "Xavfsizlik", d: "Boshqaruvchi va dispetcher rollari, kirishda ikkinchi omil, xodimlar amallarining oʻzgarmas jurnali." },
    ],
    howTitle: "Qanday ulaymiz",
    how: [
      { t: "1. Obyektni koʻramiz", d: "Domofon, kontroller, tarmoq va quvvatni tekshiramiz. Ishlayotgan texnikani qoldiramiz, yetmaganini qoʻshamiz." },
      { t: "2. Shlyuz oʻrnatamiz", d: "Server xonasidagi kichik shlyuz texnikani SAT serveri bilan bogʻlaydi. Uskuna parollari obyektda qoladi." },
      { t: "3. Uy va xonadonlarni kiritamiz", d: "Xonadonlar va yashovchilar roʻyxatini koʻchiramiz, BK xodimlari va ularning ruxsatlarini belgilaymiz." },
      { t: "4. Aholini ulaymiz", d: "Yashovchi ilovani oʻrnatib, pochtasi orqali kiradi. BKga kabinetni koʻrsatamiz va dispetcherni oʻqitamiz." },
    ],
    techTitle: "Qaysi texnika bilan ishlaydi",
    techText: "Ilova uskunani tarmoq orqali boshqaradi, shuning uchun koʻpchilik zamonaviy tizimlar mos keladi. Moslikni koʻrik paytida tekshiramiz.",
    tech: [
      "Hikvision va Dahua chaqiruv panellari va domofonlari",
      "Dahua yuzni tanish terminallari, QR orqali oʻtish ham bor",
      "ZKTeco eshik va shlagbaum kontrollerlari",
      "Elektromagnit qulflar, dovodchiklar, chiqish tugmalari",
      "Obyektda internet va server xonasida kichik shlyuz",
    ],
    faqTitle: "Koʻp beriladigan savollar",
    faq: [
      { q: "Yashovchi ilova uchun pul toʻlaydimi?", a: "Shartlarni boshqaruv kompaniyasi belgilaydi: koʻpincha ilova uy xizmati tarkibiga kiradi. Tarifni har bir yashovchi bilan emas, BK bilan kelishamiz." },
      { q: "Yashovchi telefonini almashtirsa-chi?", a: "Kirish pochta va kod orqali, shuning uchun yangi telefonda qaytadan kirish kifoya. Eski telefon esa kirish huquqini yoʻqotadi." },
      { q: "Begona odam boshqa xonadonga ulanib qolmaydimi?", a: "Xonadonni boshqaruv kompaniyasi kiritadi va egasining pochtasini biriktiradi. Qolgan yashovchilarni egasi taklif qiladi, ijarachini esa muddatga." },
      { q: "Uyda internet boʻlmasa ishlaydimi?", a: "Yuz va karta orqali oʻtishni terminalning oʻzi hal qiladi, shuning uchun u doim ishlaydi. Telefondan ochish, mehmon QR va arizalar aloqa talab qiladi." },
      { q: "Faqat bitta yoʻlakni ulasa boʻladimi?", a: "Ha. Bitta yoʻlak yoki bitta shlagbaumdan boshlab, keyin bosqichma-bosqich kengaytirish mumkin." },
    ],
    ctaTitle: "SAT Uyni boshqaruv kompaniyasiga koʻrsatamiz",
    ctaText: "Obyektingizda namoyish qilamiz va ishga tushirish uchun nima kerakligini hisoblaymiz: qaysi texnika qoladi, nima qoʻshiladi.",
    ctaButton: "Ariza qoldirish",
    otherApp: "Ish vaqtini hisobga olish — SAT Davomat",
  },
  en: {
    metaTitle: "SAT Uy — resident app: intercom on phone, guest QR pass",
    metaDesc: "An app for residents: open the entrance and barrier from a phone, issue a guest QR pass, take intercom calls anywhere, send requests to the management company, see the monthly bill and pay. Includes the management dashboard.",
    h1: "SAT Uy — resident app and management company dashboard",
    intro: "Residents open doors with a phone, call a plumber without phoning the dispatcher and see what they pay for. The management company runs requests, charges and the access log in one dashboard. The app works with intercoms, face terminals and controllers already installed on site.",
    screensTitle: "What a resident sees",
    screens: ["Doors of the building", "Guest pass", "Requests", "Monthly bill"],
    forWhomTitle: "For residents",
    forWhom: [
      { t: "Entrance and barrier from a phone", d: "Your own doors sit on the home screen; one tap opens them, even with the phone in your pocket at the gate." },
      { t: "Guests by link and QR code", d: "A resident issues a pass for a period or a single visit. The guest opens the door by link or shows the QR to the terminal." },
      { t: "Intercom calls on the phone", d: "You see who is at the door and open it straight from the notification, even when you are away." },
      { t: "Requests to the management company", d: "A request moves through accepted, in progress and done; the assignee and dispatcher replies stay visible." },
      { t: "Bill and payment", d: "Monthly charges, debt and payment via Click. Meter readings are submitted from the app." },
      { t: "Family and tenants", d: "The owner invites family members and a tenant for a fixed term and decides who may see the bill." },
    ],
    secondTitle: "For the management company",
    second: [
      { t: "A dashboard instead of a notebook", d: "Buildings, apartments, residents and access rights in one place. Doors can be opened from the dashboard too." },
      { t: "Requests with assignees", d: "The dispatcher assigns a plumber or an electrician, the resident sees the stage, and the history keeps who did what and when." },
      { t: "Charges and payments", d: "Tariffs per square metre, per apartment or per resident. Ready-made charges import from Excel or 1C." },
      { t: "News and chat", d: "A water shutdown notice reaches the whole building as a notification, and residents reply in chat." },
      { t: "Access log", d: "Who opened a door, when and how: phone, face, card or a guest QR code." },
      { t: "Security", d: "Manager and dispatcher roles, two-factor sign-in and a tamper-proof log of staff actions." },
    ],
    howTitle: "How we connect it",
    how: [
      { t: "1. Survey the site", d: "We check intercoms, controllers, network and power. Working hardware stays, missing parts are added." },
      { t: "2. Install the gateway", d: "A small gateway in the server room links the hardware to the SAT server. Equipment passwords stay on site." },
      { t: "3. Load buildings and apartments", d: "We transfer the list of apartments and residents and set up staff accounts and their rights." },
      { t: "4. Launch for residents", d: "A resident installs the app and signs in with their email. We demo the dashboard and train the dispatcher." },
    ],
    techTitle: "Supported hardware",
    techText: "The app controls equipment over the network, so most modern systems fit. Compatibility is confirmed during the survey.",
    tech: [
      "Hikvision and Dahua door stations and intercoms",
      "Dahua face recognition terminals, including QR entry",
      "ZKTeco door and barrier controllers",
      "Magnetic locks, door closers, exit buttons",
      "Internet on site and a small gateway in the server room",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "Do residents pay for the app?", a: "The management company decides: most often the app is part of the building service fee. We agree the tariff with the company, not with each resident." },
      { q: "What if a resident changes phones?", a: "Sign-in is by email with a code, so the new phone just signs in again while the old one loses access." },
      { q: "How do you stop a stranger linking to someone else's apartment?", a: "The management company creates the apartment and attaches the owner's email. The owner invites everyone else, and a tenant only for a set term." },
      { q: "Does the app work without internet in the building?", a: "Face and card access is decided by the terminal, so it always works. Phone unlocking, guest QR codes and requests need a connection." },
      { q: "Can we connect a single entrance first?", a: "Yes. You can start with one entrance or one barrier and expand step by step." },
    ],
    ctaTitle: "We will demo SAT Uy to your management company",
    ctaText: "We run a demo at your site and calculate what the launch needs: what hardware stays and what is added.",
    ctaButton: "Request a demo",
    otherApp: "Time tracking — SAT Davomat",
  },
  tr: {
    metaTitle: "SAT Uy — site uygulaması: interkom ve misafir QR",
    metaDesc: "Site sakinleri için uygulama: bina kapısını ve bariyeri telefondan açma, misafire QR geçiş, interkom çağrısını telefonda yanıtlama, yönetime talep, aylık fatura ve ödeme. Yönetim şirketi paneli dahildir.",
    h1: "SAT Uy — sakinler için uygulama ve yönetim paneli",
    intro: "Sakinler kapıları telefonla açar, tesisatçıyı dispeçere telefon etmeden çağırır ve neye ödeme yaptığını görür. Yönetim şirketi talepleri, tahakkukları ve geçiş kayıtlarını tek panelde yürütür. Uygulama sahadaki interkomlar, yüz terminalleri ve kontrolörlerle çalışır.",
    screensTitle: "Sakin ne görür",
    screens: ["Binanın kapıları", "Misafir geçişi", "Talepler", "Aylık fatura"],
    forWhomTitle: "Sakinler için",
    forWhom: [
      { t: "Kapı ve bariyer telefondan", d: "Kendi kapılarınız ana ekranda; tek dokunuşla açılır, telefon cebinizdeyken bile." },
      { t: "Misafir bağlantı ve QR ile", d: "Sakin süreli ya da tek girişlik geçiş verir. Misafir bağlantıdan açar veya QR’ı terminale gösterir." },
      { t: "İnterkom çağrısı telefonda", d: "Kapıdaki kişiyi görür, kapıyı doğrudan bildirimden açarsınız; evde olmasanız bile." },
      { t: "Yönetime talepler", d: "Talep kabul edildi, işlemde, tamamlandı aşamalarından geçer; sorumlu kişi ve dispeçer yanıtları görünür." },
      { t: "Fatura ve ödeme", d: "Aylık tahakkuk, borç ve Click ile ödeme. Sayaç değerleri de uygulamadan gönderilir." },
      { t: "Aile ve kiracılar", d: "Ev sahibi aile üyelerini ve kiracıyı süreli davet eder, faturayı kimin göreceğine kendisi karar verir." },
    ],
    secondTitle: "Yönetim şirketi için",
    second: [
      { t: "Defter yerine panel", d: "Binalar, daireler, sakinler ve yetkiler tek yerde. Kapı panelden de açılabilir." },
      { t: "Sorumlusu olan talepler", d: "Dispeçer tesisatçı ya da elektrikçi atar, sakin aşamayı görür, geçmişte kim ne yaptı kalır." },
      { t: "Tahakkuk ve ödemeler", d: "Metrekareye, daireye ya da kişi sayısına göre tarifeler. Hazır tahakkuklar Excel veya 1C’den yüklenir." },
      { t: "Duyurular ve sohbet", d: "Su kesintisi duyurusu tüm binaya bildirim olarak gider, sakin sohbetten yanıtlar." },
      { t: "Geçiş kaydı", d: "Kapıyı kim, ne zaman ve neyle açtı: telefon, yüz, kart ya da misafir QR kodu." },
      { t: "Güvenlik", d: "Yönetici ve dispeçer rolleri, iki adımlı giriş, personel işlemlerinin değiştirilemez kaydı." },
    ],
    howTitle: "Nasıl bağlıyoruz",
    how: [
      { t: "1. Sahayı geziyoruz", d: "İnterkom, kontrolör, ağ ve enerjiyi kontrol ediyoruz. Çalışan donanım kalır, eksikler tamamlanır." },
      { t: "2. Ağ geçidini kuruyoruz", d: "Sistem odasındaki küçük cihaz donanımı SAT sunucusuna bağlar. Cihaz şifreleri sahada kalır." },
      { t: "3. Bina ve daireleri giriyoruz", d: "Daire ve sakin listesini aktarıyor, yönetim personeli ile yetkilerini tanımlıyoruz." },
      { t: "4. Sakinleri başlatıyoruz", d: "Sakin uygulamayı kurar ve e-postasıyla giriş yapar. Yönetime paneli gösterir, dispeçeri eğitiriz." },
    ],
    techTitle: "Hangi donanımla çalışır",
    techText: "Uygulama cihazları ağ üzerinden yönetir; bu yüzden güncel sistemlerin çoğu uygundur. Uyumluluğu keşifte doğruluyoruz.",
    tech: [
      "Hikvision ve Dahua kapı istasyonları ve interkomları",
      "Dahua yüz tanıma terminalleri, QR ile geçiş dahil",
      "ZKTeco kapı ve bariyer kontrolörleri",
      "Manyetik kilitler, kapı kapatıcılar, çıkış butonları",
      "Sahada internet ve sistem odasında küçük ağ geçidi",
    ],
    faqTitle: "Sık sorulan sorular",
    faq: [
      { q: "Sakin uygulama için ödeme yapar mı?", a: "Koşulları yönetim şirketi belirler; çoğunlukla uygulama aidat hizmetine dâhildir. Tarifeyi her sakinle değil, şirketle görüşürüz." },
      { q: "Sakin telefonunu değiştirirse?", a: "Giriş e-posta ve kodla olduğundan yeni telefonda yeniden giriş yeterli; eski telefon erişimi kaybeder." },
      { q: "Yabancı biri başkasının dairesine bağlanabilir mi?", a: "Daireyi yönetim şirketi oluşturur ve ev sahibinin e-postasını bağlar. Diğerlerini ev sahibi davet eder, kiracıyı süreli." },
      { q: "Binada internet yokken çalışır mı?", a: "Yüz ve kart geçişine terminal karar verir, bu her zaman çalışır. Telefonla açma, misafir QR ve talepler bağlantı ister." },
      { q: "Önce tek bir girişe kurulabilir mi?", a: "Evet. Tek bina girişi ya da tek bariyerle başlayıp adım adım genişletebilirsiniz." },
    ],
    ctaTitle: "SAT Uy’u yönetim şirketinize gösterelim",
    ctaText: "Sahanızda demo yapar, devreye alma için gerekenleri hesaplarız: hangi donanım kalır, ne eklenir.",
    ctaButton: "Talep gönderin",
    otherApp: "Mesai takibi — SAT Davomat",
  },
  zh: {
    metaTitle: "SAT Uy——小区住户应用：手机对讲与访客二维码",
    metaDesc: "面向小区住户的应用：手机开启单元门与道闸，向访客发送二维码通行证，手机接听对讲，向物业报修，查看月度账单并缴费；同时包含物业管理后台。",
    h1: "SAT Uy——住户应用与物业管理后台",
    intro: "住户用手机开门，不必打电话给调度即可报修，并清楚每月费用的来源。物业在一个后台处理报修、账单与通行记录。应用对接现场已有的对讲、人脸终端与控制器。",
    screensTitle: "住户看到什么",
    screens: ["楼栋门禁", "访客通行证", "报修", "月度账单"],
    forWhomTitle: "面向住户",
    forWhom: [
      { t: "手机开单元门与道闸", d: "本人可开的门直接显示在首页，轻点即开，手机在口袋里也能在门口完成。" },
      { t: "访客用链接与二维码", d: "住户签发限时或一次性通行证，访客可用链接开门，也可将二维码对准终端。" },
      { t: "对讲呼叫转到手机", d: "看清门外是谁，直接在通知里开门；不在家也可以。" },
      { t: "向物业报修", d: "报修依次经过已受理、处理中、已完成，可见负责人与调度回复。" },
      { t: "账单与缴费", d: "按月查看费用与欠费，通过 Click 缴费；水电读数也在应用内上报。" },
      { t: "家人与租户", d: "业主邀请家人，按期限邀请租户，并自行决定谁能查看账单。" },
    ],
    secondTitle: "面向物业公司",
    second: [
      { t: "后台取代纸质台账", d: "楼栋、房号、住户与权限集中管理，也可从后台直接开门。" },
      { t: "带负责人的报修流程", d: "调度指派水电工，住户看到进度，历史记录保留谁在何时做了什么。" },
      { t: "计费与收款", d: "按面积、按户或按人数计费；已生成的账单可从 Excel 或 1C 导入。" },
      { t: "通知与聊天", d: "停水通知以推送形式发给整栋楼，住户可在聊天中回复。" },
      { t: "通行记录", d: "谁在何时用何种方式开门：手机、人脸、刷卡或访客二维码。" },
      { t: "安全", d: "经理与调度分权、登录二次验证、员工操作留痕且不可修改。" },
    ],
    howTitle: "接入流程",
    how: [
      { t: "1. 现场勘察", d: "检查对讲、控制器、网络与供电；可用设备保留，缺少的部分补齐。" },
      { t: "2. 安装网关", d: "机房内的小型网关将设备接入 SAT 服务器，设备密码保留在现场。" },
      { t: "3. 录入楼栋与房号", d: "导入房号与住户名单，创建物业员工账号并分配权限。" },
      { t: "4. 住户上线", d: "住户安装应用并用邮箱登录；我们演示后台并培训调度人员。" },
    ],
    techTitle: "支持的设备",
    techText: "应用通过网络控制设备，多数现代系统均可对接，兼容性在勘察时确认。",
    tech: [
      "海康威视与大华门口机、楼宇对讲",
      "大华人脸识别终端，含二维码通行",
      "ZKTeco 门禁与道闸控制器",
      "磁力锁、闭门器、出门按钮",
      "现场网络与机房内的小型网关",
    ],
    faqTitle: "常见问题",
    faq: [
      { q: "住户需要付费吗？", a: "由物业公司决定，多数情况下包含在物业服务中。资费与物业公司商定，而非逐户收取。" },
      { q: "住户换手机怎么办？", a: "登录方式为邮箱加验证码，新手机重新登录即可，旧手机随即失去访问权限。" },
      { q: "如何避免他人绑定别人的房号？", a: "房号由物业创建并绑定业主邮箱；其余住户由业主邀请，租户按期限邀请。" },
      { q: "楼内断网还能用吗？", a: "人脸与刷卡由终端本地判断，始终可用；手机开门、访客二维码与报修需要网络。" },
      { q: "可以先接一个单元吗？", a: "可以。先从一个单元或一处道闸开始，再逐步扩展。" },
    ],
    ctaTitle: "为贵物业演示 SAT Uy",
    ctaText: "我们到现场演示，并核算上线所需：哪些设备保留、需要补充什么。",
    ctaButton: "提交需求",
    otherApp: "考勤管理——SAT Davomat",
  },
};
