// АВТОГЕН: тип (имя категории) → slug канонического лонгрида (category:<slug>)
export const TYPE_LONGREAD_SLUG: Record<string,string> = {
  "HD-камеры (Turbo HD)": "hik-hd-cameras",
  "HDCVI-камеры": "hdcvi-cameras",
  "HDCVI-регистраторы": "hdcvi-recorders",
  "IP-видеорегистраторы (NVR)": "hik-nvr",
  "IP-камеры": "hik-ip-cameras",
  "IP-телефония": "pxt-voip",
  "Mesh-системы": "mercusys-mesh",
  "PON-оборудование": "pxt-pon",
  "PTZ — поворотные камеры": "avigilon-ptz",
  "PTZ-камеры": "hik-ptz-cameras",
  "SFP-модули и трансиверы": "pxt-sfp",
  "USB-адаптеры": "mercusys-usb",
  "Wi-Fi камеры": "tapo-cameras",
  "Wi-Fi мосты": "witek-bridges",
  "Wi-Fi точки доступа": "tplink-wifi",
  "Аксессуары": "mikrotik-accessories",
  "Беспроводное и сетевое": "pxt-wireless",
  "Беспроводные камеры": "hik-wireless-cameras",
  "Видеодомофоны": "tapo-doorbells",
  "Видеорегистраторы (DVR)": "hik-dvr",
  "Внутренние мониторы": "indoor-monitors",
  "Вызывные панели": "door-stations",
  "Декодеры и контроллеры стен": "decoders",
  "Детекторы и датчики": "detectors",
  "Дисплеи и мониторы": "displei-hik",
  "Домофония": "hik-intercoms",
  "Жёсткие диски": "prochee-hdd",
  "Замки и СКУД": "kanihad-locks",
  "ИБП и электропитание": "pxt-ups",
  "Извещатели": "rubezh-detectors",
  "Инструменты": "pxt-tools",
  "Кабель": "prochee-cable",
  "Коммутаторы": "pxt-switches",
  "Контроллеры доступа": "access-controllers",
  "Контрольные панели": "alarm-panels",
  "Кронштейны и аксессуары": "prochee-accessories",
  "Купольные камеры": "avigilon-domes",
  "Маршрутизаторы": "mikrotik-routers",
  "Мастер-станции": "master-stations",
  "Металлодетекторы": "metal-detectors",
  "Оборудование": "bolid-misc",
  "Оповещатели": "rubezh-sirens",
  "Оповещение": "prochee-pa",
  "Оптика и HDMI": "prochee-optics",
  "Оптика и аксессуары": "pxt-fiber",
  "Оптические коммутаторы": "witek-optical",
  "Охранная сигнализация AX PRO": "hik-axpro",
  "Панорамные камеры 360°": "avigilon-panoramic",
  "Пожарная безопасность": "prochee-fire",
  "Приборы и модули": "rubezh-panels",
  "Программное обеспечение": "bolid-software",
  "Проектное оборудование": "hik-project",
  "Пульты": "bolid-keypads",
  "Радиомосты": "mikrotik-wireless",
  "СКС (витая пара)": "pxt-scs",
  "Серверное оборудование": "pxt-server",
  "Сетевые камеры": "network-cameras",
  "Системы распознавания номеров (ANPR)": "anpr",
  "Специальные камеры": "avigilon-specialty",
  "Считыватели и конвертеры": "zkteco-readers",
  "Телекоммуникационные шкафы": "pxt-racks",
  "Терминалы доступа": "zkteco-terminals",
  "Терминалы и считыватели": "hik-access-terminals",
  "Точки доступа и роутеры": "witek-wifi",
  "Турникеты и шлагбаумы": "hik-turnstiles",
  "Умный дом": "pxt-smart",
  "Усилители сигнала": "mercusys-extenders",
  "Цилиндрические и корпусные камеры": "avigilon-bullet",
};
